version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - aws iam delete-policy --policy-arn arn:aws:iam::123456789:policy/s3-all-read-cli
      - aws iam create-policy --policy-name s3-all-read-cli --policy-document file://s3-bucket-policy.json 
artifacts:
  files:
    - '**/*'
